pdp:
    host: "ogc.demo.secure-dimensions.de"
    port: 443
    endpoint: "authzforce-ce"
    ssl_verify: False
    proxy_activate: False
auth:
    auth_type: none
    token: "71c05c9fdd67a54c1ba1cff901921930d6ee6709"


