  version: "3.8"

  services:
    # Authzforce is a XACML Server PDP
    authzforce:
      image: fiware/authzforce-ce-server:release-11.0.0
      container_name: authzforce
      ports:
        - 8080:8080 # localhost:8080
      healthcheck:
        test: curl --fail -s http://localhost:8080/authzforce-ce/version || exit 1